# Actividad 2-2
- Jorge Emiliano Pomar 
- A01709338
- 20 de febrero de 2025

## Ejercicio 1

(20 pts) Con este archivo, explora y convierte las columnas necesarias a series de tiempo. Justifica el tipo de dato utilizado.

Justificación:

- policy_bind_date: Se convierte a datetime ya que es una fecha con formato MM/dd/yyyy.
- incident_date: Se convierte a datetime ya que es una fecha con formato MM/dd/yyyy.
- auto_year: Dejo auto year como int porque es solamente un año.
- incident_hour_of_the_day: Dejo incident_hour_of_the_day como int porque es una hora del día.

In [2]:
import pandas as pd

df = pd.read_csv(
    "insurance_claims.csv",
    parse_dates=[
        "policy_bind_date",
        "incident_date",
    ],
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: datetime64[ns](2), float64(2), int64(17), object(19)
memory usage: 312.6+ KB

## Ejercicio 2

(20 pts) Establece como índice la columna incident_date y reporta la cantidad de incidentes en febrero del 2015.

In [3]:
df.index = df.incident_date
df.loc["2015-02"]

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
incident_date,,,,,,,,,,,,,,,,,,,,,
2015-02-22,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
2015-02-17,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN
2015-02-27,165,37,429027,1990-02-03,IL,100/300,1000,1137.03,0,603195,...,YES,51590,9380,9380,32830,Audi,A5,2015,N,NaN
2015-02-15,447,61,214618,1999-05-29,OH,100/300,2000,1137.16,0,615561,...,YES,114920,17680,17680,79560,Audi,A3,2006,N,NaN
2015-02-22,70,26,558938,2005-06-08,OH,500/1000,1000,1199.44,5000000,619884,...,YES,52110,5790,5790,40530,Nissan,Maxima,2012,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-02-06,257,44,109392,2006-07-12,OH,100/300,1000,1280.88,0,433981,...,NO,46980,0,5220,41760,Accura,TL,2002,N,NaN
2015-02-17,124,28,674570,2001-12-08,OH,250/500,1000,1235.14,0,443567,...,?,60200,6020,6020,48160,Volkswagen,Passat,2012,N,NaN
2015-02-22,3,38,941851,1991-07-16,OH,500/1000,1000,1310.80,0,431289,...,?,87200,17440,8720,61040,Honda,Accord,2006,N,NaN
2015-02-26,458,62,533940,2011-11-18,IL,500/1000,2000,1356.92,5000000,441714,...,YES,46980,5220,5220,36540,Audi,A5,1998,N,NaN
2015-02-26,456,60,556080,1996-11-11,OH,250/500,1000,766.19,0,612260,...,?,5060,460,920,3680,Mercedes,E400,2007,N,NaN

## Ejercicio 3

(20 pts) Crea una columna llamada days_till_incident donde se muestren los días que tomó desde el registro de fecha de vinculación de poliza (bind date) hasta el incidente. Reporta el promedio de estos días e indica y justifica el tipo de dato de tiempo apropiado.

**Justificación**: Salió timedelta porque es un tipo de dato que impone python cuando hay una operación de diferencia de fechas. Tal cual calcula la duración. En este caso sale 03:21:36 porque saqué el promedio. Podría ser confudo porque fue la diferencia entre 2 fechas sin tiempo.

In [4]:
df["days_till_incident"] = df["incident_date"] - df["policy_bind_date"]
promedio = df["days_till_incident"].mean()
print(promedio)
df
df.info()

4739 days 03:21:36
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1000 entries, 2015-01-25 to 2015-02-26
Data columns (total 41 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
 40  days_till_incident           1000 non-null   timedelta64[ns]
dtypes: datetime64[ns](2), float64(2), int64(17), object(19), timedelta64[ns](1)
memory usage: 328.1+ KB

## Ejercicio 4

(20 pts) Crea otra columna llamada "prospected_incident" donde se muestre la fecha de incidente según el promedio. Responde, ¿porqué el cambio de tipo de dato de tiempo?

**Justificación**: Cambió porque se le sumó un timedelta con las horas que acumuló del promedio a una fecha sin tiempo. Se cambió a un datetime.

In [5]:
df["prospected_incident"] = df["policy_bind_date"] + promedio
df["prospected_incident"]
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1000 entries, 2015-01-25 to 2015-02-26
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
 40  days_till_incident           1000 non-null   timedelta64[ns]
 41  prospected_incident          1000 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(17), object(19), timedelta64[ns](1)
memory usage: 335.9+ KB

## Ejercicio 5

(10 pts) En la columna collision_type reemplaza los '?' por 'desconocido'.

In [6]:
df.collision_type.replace("?", "desconocido")

incident_date
2015-01-25     Side Collision
2015-01-21        desconocido
2015-02-22     Rear Collision
2015-01-10    Front Collision
2015-02-17        desconocido
                   ...
2015-02-22    Front Collision
2015-01-24     Rear Collision
2015-01-23     Side Collision
2015-02-26     Rear Collision
2015-02-26        desconocido
Name: collision_type, Length: 1000, dtype: object

## Ejercicio 6

(10 pts) Con la columna incident_type, reporta cuántos incidentes de colisión se presentaron. Utiliza funciones de texto.

In [7]:
incidentes = df["incident_type"].str.contains("Collision").sum()
print(f"Número de incidentes de colisión: {incidentes}")

Número de incidentes de colisión: 822