# Minimum Distance Classifier
- Jorge Emiliano Pomar 
- A01709338
- 26 de marzo de 2025

Cargar a dataframe.

In [22]:
import pandas as pd

df = pd.read_csv('iris.csv')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [24]:
train_data = df.groupby('class').sample(n=45)
train_data

     sepal length  sepal width  petal length  petal width           class
44            5.1          3.8           1.9          0.4     Iris-setosa
45            4.8          3.0           1.4          0.3     Iris-setosa
32            5.2          4.1           1.5          0.1     Iris-setosa
11            4.8          3.4           1.6          0.2     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
107           7.3          2.9           6.3          1.8  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica

[135 rows x 5 columns]

In [25]:
df_prueba = df.drop(train_data.index)

In [26]:
df_prueba

     sepal length  sepal width  petal length  petal width            class
21            5.1          3.7           1.5          0.4      Iris-setosa
24            4.8          3.4           1.9          0.2      Iris-setosa
27            5.2          3.5           1.5          0.2      Iris-setosa
36            5.5          3.5           1.3          0.2      Iris-setosa
47            4.6          3.2           1.4          0.2      Iris-setosa
63            6.1          2.9           4.7          1.4  Iris-versicolor
68            6.2          2.2           4.5          1.5  Iris-versicolor
73            6.1          2.8           4.7          1.2  Iris-versicolor
76            6.8          2.8           4.8          1.4  Iris-versicolor
99            5.7          2.8           4.1          1.3  Iris-versicolor
112           6.8          3.0           5.5          2.1   Iris-virginica
121           5.6          2.8           4.9          2.0   Iris-virginica
133           6.3          2.8           5.1          1.5   Iris-virginica
135           7.7          3.0           6.1          2.3   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica

Vector de promedio por cada clase.

In [27]:
mean_vectors = train_data.groupby('class').mean()

Con esta funciÃ³n clasificamos los datos de entrenamiento. La clasificacion se hace despues de calcular la minima distancia euclidiana. DespuÃ©s se aplica a cada axis del dataframe.

In [32]:
def clasificador(row):
    distances = mean_vectors.apply(
        lambda mean: ((row[['sepal length', 'sepal width', 'petal length', 'petal width']] - mean) ** 2).sum() ** 0.5,
        axis=1
    )
    return distances.idxmin()

Genera una columna nueva con las clases clasificadas por la distancia mÃ¡s corta. Con apply, se implementa la funciÃ³n de clasificador sobre cada axis del df de los datos de prueba (15 restantes). Se despliegan con la clase original y la predicciÃ³n.

In [ ]:
df_prueba['predicciÃ³n'] = df_prueba.apply(clasificador, axis=1)

df_prueba[['class', 'predicciÃ³n']]

               class       predicciÃ³n
21       Iris-setosa      Iris-setosa
24       Iris-setosa      Iris-setosa
27       Iris-setosa      Iris-setosa
36       Iris-setosa      Iris-setosa
47       Iris-setosa      Iris-setosa
63   Iris-versicolor  Iris-versicolor
68   Iris-versicolor  Iris-versicolor
73   Iris-versicolor  Iris-versicolor
76   Iris-versicolor   Iris-virginica
99   Iris-versicolor  Iris-versicolor
112   Iris-virginica   Iris-virginica
121   Iris-virginica  Iris-versicolor
133   Iris-virginica   Iris-virginica
135   Iris-virginica   Iris-virginica
147   Iris-virginica   Iris-virginica